# Generated by Django 5.0.6 on 2024-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitoredSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("check_interval", models.IntegerField()),
                (
                    "keyword",
                    models.CharField(default="default_keyword", max_length=100),
                ),
            ],
        ),
    ]
