# Generated by Django 5.0.6 on 2024-07-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredsite',
            options={'verbose_name': 'Monitored Page', 'verbose_name_plural': 'Monitored Pages'},
        ),
    ]
