# Generated by Django 5.0.6 on 2024-07-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_monitoredsite_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoredsite",
            name="check_interval",
            field=models.PositiveIntegerField(),
        ),
    ]
