# Generated by Django 5.0.6 on 2024-07-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_monitoredsite_last_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.monitoredsite')),
            ],
        ),
    ]
